/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BackwardTraceResult {
  'tanks' : Array<TankUsage>,
  'muesliLogs' : Array<DateIngredients>,
  'batchCode' : string,
}
export interface DashboardStats {
  'holdsCount' : bigint,
  'totalBatchesThisWeek' : bigint,
  'rawMaterialsConsumedThisWeek' : bigint,
}
export interface DateIngredients {
  'run' : string,
  'date' : string,
  'shift' : string,
  'ingredients' : Array<IngredientRow>,
  'product' : string,
}
export interface DateRange { 'toDate' : DateText, 'fromDate' : DateText }
export type DateText = string;
export interface FlaggedRecord {
  'linkedLotNumbers' : Array<string>,
  'linkedBatchCodes' : Array<string>,
  'tankEntry' : TankRoomLogEntry,
}
export interface ForwardTraceResult {
  'lotNo' : string,
  'muesliDates' : Array<string>,
  'packingEntries' : Array<PackingReference>,
}
export interface IngredientRow {
  'qty' : string,
  'issueFromStores' : string,
  'lotNo' : string,
  'closingStock' : string,
  'ingredientName' : string,
  'openingStock' : string,
}
export interface MuesliProcessLogEntry {
  'id' : bigint,
  'run' : string,
  'date' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'shift' : string,
  'updatedAt' : [] | [bigint],
  'updatedBy' : [] | [string],
  'ingredients' : Array<IngredientRow>,
  'product' : string,
}
export interface MuesliProcessLogInput {
  'run' : string,
  'date' : string,
  'shift' : string,
  'ingredients' : Array<IngredientRow>,
  'product' : string,
}
export interface PackingLogEntry {
  'id' : bigint,
  'mrp' : string,
  'bulkBagLotNo' : string,
  'bestBefore' : string,
  'caseCode' : string,
  'crew' : string,
  'date' : string,
  'netWeight' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'productName' : string,
  'updatedAt' : [] | [bigint],
  'updatedBy' : [] | [string],
  'tankBatchCodes' : Array<string>,
  'casePartitionSupplier' : string,
  'variety' : string,
  'machineNo' : string,
  'casePartitionLotNo' : string,
  'batchCode' : string,
  'bulkBagSupplier' : string,
  'mfgDate' : string,
}
export interface PackingLogInput {
  'mrp' : string,
  'bulkBagLotNo' : string,
  'bestBefore' : string,
  'caseCode' : string,
  'crew' : string,
  'date' : string,
  'netWeight' : string,
  'productName' : string,
  'tankBatchCodes' : Array<string>,
  'casePartitionSupplier' : string,
  'variety' : string,
  'machineNo' : string,
  'casePartitionLotNo' : string,
  'batchCode' : string,
  'bulkBagSupplier' : string,
  'mfgDate' : string,
}
export interface PackingReference {
  'date' : string,
  'productName' : string,
  'foodTankNos' : Array<string>,
  'batchCode' : string,
}
export interface ShiftReport {
  'tankEntries' : Array<TankRoomLogEntry>,
  'rawMaterialEntries' : Array<MuesliProcessLogEntry>,
  'date' : string,
  'shift' : string,
  'packingEntries' : Array<PackingLogEntry>,
}
export interface TankRoomLogEntry {
  'id' : bigint,
  'remark' : string,
  'productRun' : string,
  'tankStatus' : TankStatus,
  'date' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'fillingTimeIn' : string,
  'fillingTimeOut' : string,
  'shift' : string,
  'updatedAt' : [] | [bigint],
  'updatedBy' : [] | [string],
  'cleaned' : boolean,
  'permanentTankNumber' : string,
  'reasonForHold' : string,
  'foodTankNo' : string,
  'correctiveAction' : string,
  'batchCode' : string,
}
export interface TankRoomLogInput {
  'remark' : string,
  'productRun' : string,
  'tankStatus' : TankStatus,
  'date' : string,
  'fillingTimeIn' : string,
  'fillingTimeOut' : string,
  'shift' : string,
  'cleaned' : boolean,
  'permanentTankNumber' : string,
  'reasonForHold' : string,
  'foodTankNo' : string,
  'correctiveAction' : string,
  'batchCode' : string,
}
export type TankStatus = { 'Feed' : null } |
  { 'Food' : null } |
  { 'Hold' : null };
export interface TankUsage {
  'date' : string,
  'shift' : string,
  'foodTankNo' : string,
}
export interface _SERVICE {
  'addMuesliProcessLog' : ActorMethod<
    [MuesliProcessLogInput],
    { 'ok' : MuesliProcessLogEntry } |
      { 'err' : string }
  >,
  'addPackingLog' : ActorMethod<
    [PackingLogInput],
    { 'ok' : PackingLogEntry } |
      { 'err' : string }
  >,
  'addTankRoomLog' : ActorMethod<
    [TankRoomLogInput],
    { 'ok' : TankRoomLogEntry } |
      { 'err' : string }
  >,
  'backwardTraceability' : ActorMethod<[string], BackwardTraceResult>,
  'checkDuplicateBatchCode' : ActorMethod<[string], boolean>,
  'checkDuplicateLotNumber' : ActorMethod<[string, string], boolean>,
  'deleteMuesliProcessLog' : ActorMethod<[bigint], boolean>,
  'deletePackingLog' : ActorMethod<[bigint], boolean>,
  'deleteTankRoomLog' : ActorMethod<[bigint], boolean>,
  'forwardTraceability' : ActorMethod<[string], ForwardTraceResult>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getFlaggedRecords' : ActorMethod<[], Array<FlaggedRecord>>,
  'getMuesliProcessLogs' : ActorMethod<
    [[] | [DateRange]],
    Array<MuesliProcessLogEntry>
  >,
  'getPackingLogs' : ActorMethod<[[] | [DateRange]], Array<PackingLogEntry>>,
  'getShiftReport' : ActorMethod<[string, string], ShiftReport>,
  'getTankRoomLogs' : ActorMethod<[[] | [DateRange]], Array<TankRoomLogEntry>>,
  'updateMuesliProcessLog' : ActorMethod<
    [MuesliProcessLogEntry],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updatePackingLog' : ActorMethod<
    [PackingLogEntry],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updateTankRoomLog' : ActorMethod<
    [TankRoomLogEntry],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];