/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const IngredientRow = IDL.Record({
  'qty' : IDL.Text,
  'issueFromStores' : IDL.Text,
  'lotNo' : IDL.Text,
  'closingStock' : IDL.Text,
  'ingredientName' : IDL.Text,
  'openingStock' : IDL.Text,
});
export const MuesliProcessLogInput = IDL.Record({
  'run' : IDL.Text,
  'date' : IDL.Text,
  'shift' : IDL.Text,
  'ingredients' : IDL.Vec(IngredientRow),
  'product' : IDL.Text,
});
export const MuesliProcessLogEntry = IDL.Record({
  'id' : IDL.Nat,
  'run' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'shift' : IDL.Text,
  'updatedAt' : IDL.Opt(IDL.Int),
  'updatedBy' : IDL.Opt(IDL.Text),
  'ingredients' : IDL.Vec(IngredientRow),
  'product' : IDL.Text,
});
export const PackingLogInput = IDL.Record({
  'mrp' : IDL.Text,
  'bulkBagLotNo' : IDL.Text,
  'bestBefore' : IDL.Text,
  'caseCode' : IDL.Text,
  'crew' : IDL.Text,
  'date' : IDL.Text,
  'netWeight' : IDL.Text,
  'productName' : IDL.Text,
  'tankBatchCodes' : IDL.Vec(IDL.Text),
  'casePartitionSupplier' : IDL.Text,
  'variety' : IDL.Text,
  'machineNo' : IDL.Text,
  'casePartitionLotNo' : IDL.Text,
  'batchCode' : IDL.Text,
  'bulkBagSupplier' : IDL.Text,
  'mfgDate' : IDL.Text,
});
export const PackingLogEntry = IDL.Record({
  'id' : IDL.Nat,
  'mrp' : IDL.Text,
  'bulkBagLotNo' : IDL.Text,
  'bestBefore' : IDL.Text,
  'caseCode' : IDL.Text,
  'crew' : IDL.Text,
  'date' : IDL.Text,
  'netWeight' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'productName' : IDL.Text,
  'updatedAt' : IDL.Opt(IDL.Int),
  'updatedBy' : IDL.Opt(IDL.Text),
  'tankBatchCodes' : IDL.Vec(IDL.Text),
  'casePartitionSupplier' : IDL.Text,
  'variety' : IDL.Text,
  'machineNo' : IDL.Text,
  'casePartitionLotNo' : IDL.Text,
  'batchCode' : IDL.Text,
  'bulkBagSupplier' : IDL.Text,
  'mfgDate' : IDL.Text,
});
export const TankStatus = IDL.Variant({
  'Feed' : IDL.Null,
  'Food' : IDL.Null,
  'Hold' : IDL.Null,
});
export const TankRoomLogInput = IDL.Record({
  'remark' : IDL.Text,
  'productRun' : IDL.Text,
  'tankStatus' : TankStatus,
  'date' : IDL.Text,
  'fillingTimeIn' : IDL.Text,
  'fillingTimeOut' : IDL.Text,
  'shift' : IDL.Text,
  'cleaned' : IDL.Bool,
  'permanentTankNumber' : IDL.Text,
  'reasonForHold' : IDL.Text,
  'foodTankNo' : IDL.Text,
  'correctiveAction' : IDL.Text,
  'batchCode' : IDL.Text,
});
export const TankRoomLogEntry = IDL.Record({
  'id' : IDL.Nat,
  'remark' : IDL.Text,
  'productRun' : IDL.Text,
  'tankStatus' : TankStatus,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'fillingTimeIn' : IDL.Text,
  'fillingTimeOut' : IDL.Text,
  'shift' : IDL.Text,
  'updatedAt' : IDL.Opt(IDL.Int),
  'updatedBy' : IDL.Opt(IDL.Text),
  'cleaned' : IDL.Bool,
  'permanentTankNumber' : IDL.Text,
  'reasonForHold' : IDL.Text,
  'foodTankNo' : IDL.Text,
  'correctiveAction' : IDL.Text,
  'batchCode' : IDL.Text,
});
export const TankUsage = IDL.Record({
  'date' : IDL.Text,
  'shift' : IDL.Text,
  'foodTankNo' : IDL.Text,
});
export const DateIngredients = IDL.Record({
  'run' : IDL.Text,
  'date' : IDL.Text,
  'shift' : IDL.Text,
  'ingredients' : IDL.Vec(IngredientRow),
  'product' : IDL.Text,
});
export const BackwardTraceResult = IDL.Record({
  'tanks' : IDL.Vec(TankUsage),
  'muesliLogs' : IDL.Vec(DateIngredients),
  'batchCode' : IDL.Text,
});
export const PackingReference = IDL.Record({
  'date' : IDL.Text,
  'productName' : IDL.Text,
  'foodTankNos' : IDL.Vec(IDL.Text),
  'batchCode' : IDL.Text,
});
export const ForwardTraceResult = IDL.Record({
  'lotNo' : IDL.Text,
  'muesliDates' : IDL.Vec(IDL.Text),
  'packingEntries' : IDL.Vec(PackingReference),
});
export const DashboardStats = IDL.Record({
  'holdsCount' : IDL.Nat,
  'totalBatchesThisWeek' : IDL.Nat,
  'rawMaterialsConsumedThisWeek' : IDL.Nat,
});
export const FlaggedRecord = IDL.Record({
  'linkedLotNumbers' : IDL.Vec(IDL.Text),
  'linkedBatchCodes' : IDL.Vec(IDL.Text),
  'tankEntry' : TankRoomLogEntry,
});
export const DateText = IDL.Text;
export const DateRange = IDL.Record({
  'toDate' : DateText,
  'fromDate' : DateText,
});
export const ShiftReport = IDL.Record({
  'tankEntries' : IDL.Vec(TankRoomLogEntry),
  'rawMaterialEntries' : IDL.Vec(MuesliProcessLogEntry),
  'date' : IDL.Text,
  'shift' : IDL.Text,
  'packingEntries' : IDL.Vec(PackingLogEntry),
});

export const idlService = IDL.Service({
  'addMuesliProcessLog' : IDL.Func(
      [MuesliProcessLogInput],
      [IDL.Variant({ 'ok' : MuesliProcessLogEntry, 'err' : IDL.Text })],
      [],
    ),
  'addPackingLog' : IDL.Func(
      [PackingLogInput],
      [IDL.Variant({ 'ok' : PackingLogEntry, 'err' : IDL.Text })],
      [],
    ),
  'addTankRoomLog' : IDL.Func(
      [TankRoomLogInput],
      [IDL.Variant({ 'ok' : TankRoomLogEntry, 'err' : IDL.Text })],
      [],
    ),
  'backwardTraceability' : IDL.Func(
      [IDL.Text],
      [BackwardTraceResult],
      ['query'],
    ),
  'checkDuplicateBatchCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'checkDuplicateLotNumber' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'deleteMuesliProcessLog' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePackingLog' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTankRoomLog' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'forwardTraceability' : IDL.Func([IDL.Text], [ForwardTraceResult], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getFlaggedRecords' : IDL.Func([], [IDL.Vec(FlaggedRecord)], ['query']),
  'getMuesliProcessLogs' : IDL.Func(
      [IDL.Opt(DateRange)],
      [IDL.Vec(MuesliProcessLogEntry)],
      ['query'],
    ),
  'getPackingLogs' : IDL.Func(
      [IDL.Opt(DateRange)],
      [IDL.Vec(PackingLogEntry)],
      ['query'],
    ),
  'getShiftReport' : IDL.Func([IDL.Text, IDL.Text], [ShiftReport], ['query']),
  'getTankRoomLogs' : IDL.Func(
      [IDL.Opt(DateRange)],
      [IDL.Vec(TankRoomLogEntry)],
      ['query'],
    ),
  'updateMuesliProcessLog' : IDL.Func(
      [MuesliProcessLogEntry],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updatePackingLog' : IDL.Func(
      [PackingLogEntry],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updateTankRoomLog' : IDL.Func(
      [TankRoomLogEntry],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const IngredientRow = IDL.Record({
    'qty' : IDL.Text,
    'issueFromStores' : IDL.Text,
    'lotNo' : IDL.Text,
    'closingStock' : IDL.Text,
    'ingredientName' : IDL.Text,
    'openingStock' : IDL.Text,
  });
  const MuesliProcessLogInput = IDL.Record({
    'run' : IDL.Text,
    'date' : IDL.Text,
    'shift' : IDL.Text,
    'ingredients' : IDL.Vec(IngredientRow),
    'product' : IDL.Text,
  });
  const MuesliProcessLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'run' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'shift' : IDL.Text,
    'updatedAt' : IDL.Opt(IDL.Int),
    'updatedBy' : IDL.Opt(IDL.Text),
    'ingredients' : IDL.Vec(IngredientRow),
    'product' : IDL.Text,
  });
  const PackingLogInput = IDL.Record({
    'mrp' : IDL.Text,
    'bulkBagLotNo' : IDL.Text,
    'bestBefore' : IDL.Text,
    'caseCode' : IDL.Text,
    'crew' : IDL.Text,
    'date' : IDL.Text,
    'netWeight' : IDL.Text,
    'productName' : IDL.Text,
    'tankBatchCodes' : IDL.Vec(IDL.Text),
    'casePartitionSupplier' : IDL.Text,
    'variety' : IDL.Text,
    'machineNo' : IDL.Text,
    'casePartitionLotNo' : IDL.Text,
    'batchCode' : IDL.Text,
    'bulkBagSupplier' : IDL.Text,
    'mfgDate' : IDL.Text,
  });
  const PackingLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'mrp' : IDL.Text,
    'bulkBagLotNo' : IDL.Text,
    'bestBefore' : IDL.Text,
    'caseCode' : IDL.Text,
    'crew' : IDL.Text,
    'date' : IDL.Text,
    'netWeight' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'productName' : IDL.Text,
    'updatedAt' : IDL.Opt(IDL.Int),
    'updatedBy' : IDL.Opt(IDL.Text),
    'tankBatchCodes' : IDL.Vec(IDL.Text),
    'casePartitionSupplier' : IDL.Text,
    'variety' : IDL.Text,
    'machineNo' : IDL.Text,
    'casePartitionLotNo' : IDL.Text,
    'batchCode' : IDL.Text,
    'bulkBagSupplier' : IDL.Text,
    'mfgDate' : IDL.Text,
  });
  const TankStatus = IDL.Variant({
    'Feed' : IDL.Null,
    'Food' : IDL.Null,
    'Hold' : IDL.Null,
  });
  const TankRoomLogInput = IDL.Record({
    'remark' : IDL.Text,
    'productRun' : IDL.Text,
    'tankStatus' : TankStatus,
    'date' : IDL.Text,
    'fillingTimeIn' : IDL.Text,
    'fillingTimeOut' : IDL.Text,
    'shift' : IDL.Text,
    'cleaned' : IDL.Bool,
    'permanentTankNumber' : IDL.Text,
    'reasonForHold' : IDL.Text,
    'foodTankNo' : IDL.Text,
    'correctiveAction' : IDL.Text,
    'batchCode' : IDL.Text,
  });
  const TankRoomLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'remark' : IDL.Text,
    'productRun' : IDL.Text,
    'tankStatus' : TankStatus,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'fillingTimeIn' : IDL.Text,
    'fillingTimeOut' : IDL.Text,
    'shift' : IDL.Text,
    'updatedAt' : IDL.Opt(IDL.Int),
    'updatedBy' : IDL.Opt(IDL.Text),
    'cleaned' : IDL.Bool,
    'permanentTankNumber' : IDL.Text,
    'reasonForHold' : IDL.Text,
    'foodTankNo' : IDL.Text,
    'correctiveAction' : IDL.Text,
    'batchCode' : IDL.Text,
  });
  const TankUsage = IDL.Record({
    'date' : IDL.Text,
    'shift' : IDL.Text,
    'foodTankNo' : IDL.Text,
  });
  const DateIngredients = IDL.Record({
    'run' : IDL.Text,
    'date' : IDL.Text,
    'shift' : IDL.Text,
    'ingredients' : IDL.Vec(IngredientRow),
    'product' : IDL.Text,
  });
  const BackwardTraceResult = IDL.Record({
    'tanks' : IDL.Vec(TankUsage),
    'muesliLogs' : IDL.Vec(DateIngredients),
    'batchCode' : IDL.Text,
  });
  const PackingReference = IDL.Record({
    'date' : IDL.Text,
    'productName' : IDL.Text,
    'foodTankNos' : IDL.Vec(IDL.Text),
    'batchCode' : IDL.Text,
  });
  const ForwardTraceResult = IDL.Record({
    'lotNo' : IDL.Text,
    'muesliDates' : IDL.Vec(IDL.Text),
    'packingEntries' : IDL.Vec(PackingReference),
  });
  const DashboardStats = IDL.Record({
    'holdsCount' : IDL.Nat,
    'totalBatchesThisWeek' : IDL.Nat,
    'rawMaterialsConsumedThisWeek' : IDL.Nat,
  });
  const FlaggedRecord = IDL.Record({
    'linkedLotNumbers' : IDL.Vec(IDL.Text),
    'linkedBatchCodes' : IDL.Vec(IDL.Text),
    'tankEntry' : TankRoomLogEntry,
  });
  const DateText = IDL.Text;
  const DateRange = IDL.Record({ 'toDate' : DateText, 'fromDate' : DateText });
  const ShiftReport = IDL.Record({
    'tankEntries' : IDL.Vec(TankRoomLogEntry),
    'rawMaterialEntries' : IDL.Vec(MuesliProcessLogEntry),
    'date' : IDL.Text,
    'shift' : IDL.Text,
    'packingEntries' : IDL.Vec(PackingLogEntry),
  });
  
  return IDL.Service({
    'addMuesliProcessLog' : IDL.Func(
        [MuesliProcessLogInput],
        [IDL.Variant({ 'ok' : MuesliProcessLogEntry, 'err' : IDL.Text })],
        [],
      ),
    'addPackingLog' : IDL.Func(
        [PackingLogInput],
        [IDL.Variant({ 'ok' : PackingLogEntry, 'err' : IDL.Text })],
        [],
      ),
    'addTankRoomLog' : IDL.Func(
        [TankRoomLogInput],
        [IDL.Variant({ 'ok' : TankRoomLogEntry, 'err' : IDL.Text })],
        [],
      ),
    'backwardTraceability' : IDL.Func(
        [IDL.Text],
        [BackwardTraceResult],
        ['query'],
      ),
    'checkDuplicateBatchCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'checkDuplicateLotNumber' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'deleteMuesliProcessLog' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePackingLog' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTankRoomLog' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'forwardTraceability' : IDL.Func(
        [IDL.Text],
        [ForwardTraceResult],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getFlaggedRecords' : IDL.Func([], [IDL.Vec(FlaggedRecord)], ['query']),
    'getMuesliProcessLogs' : IDL.Func(
        [IDL.Opt(DateRange)],
        [IDL.Vec(MuesliProcessLogEntry)],
        ['query'],
      ),
    'getPackingLogs' : IDL.Func(
        [IDL.Opt(DateRange)],
        [IDL.Vec(PackingLogEntry)],
        ['query'],
      ),
    'getShiftReport' : IDL.Func([IDL.Text, IDL.Text], [ShiftReport], ['query']),
    'getTankRoomLogs' : IDL.Func(
        [IDL.Opt(DateRange)],
        [IDL.Vec(TankRoomLogEntry)],
        ['query'],
      ),
    'updateMuesliProcessLog' : IDL.Func(
        [MuesliProcessLogEntry],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updatePackingLog' : IDL.Func(
        [PackingLogEntry],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updateTankRoomLog' : IDL.Func(
        [TankRoomLogEntry],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };