/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ForwardTraceResult {
    lotNo: string;
    muesliDates: Array<string>;
    packingEntries: Array<PackingReference>;
}
export interface FlaggedRecord {
    linkedLotNumbers: Array<string>;
    linkedBatchCodes: Array<string>;
    tankEntry: TankRoomLogEntry;
}
export interface MuesliProcessLogInput {
    run: string;
    date: string;
    shift: string;
    ingredients: Array<IngredientRow>;
    product: string;
}
export interface TankRoomLogInput {
    remark: string;
    productRun: string;
    tankStatus: TankStatus;
    date: string;
    fillingTimeIn: string;
    fillingTimeOut: string;
    shift: string;
    cleaned: boolean;
    permanentTankNumber: string;
    reasonForHold: string;
    foodTankNo: string;
    correctiveAction: string;
    batchCode: string;
}
export interface PackingLogInput {
    mrp: string;
    bulkBagLotNo: string;
    bestBefore: string;
    caseCode: string;
    crew: string;
    date: string;
    netWeight: string;
    productName: string;
    tankBatchCodes: Array<string>;
    casePartitionSupplier: string;
    variety: string;
    machineNo: string;
    casePartitionLotNo: string;
    batchCode: string;
    bulkBagSupplier: string;
    mfgDate: string;
}
export interface ShiftReport {
    tankEntries: Array<TankRoomLogEntry>;
    rawMaterialEntries: Array<MuesliProcessLogEntry>;
    date: string;
    shift: string;
    packingEntries: Array<PackingLogEntry>;
}
export interface TankUsage {
    date: string;
    shift: string;
    foodTankNo: string;
}
export interface DashboardStats {
    holdsCount: bigint;
    totalBatchesThisWeek: bigint;
    rawMaterialsConsumedThisWeek: bigint;
}
export interface BackwardTraceResult {
    tanks: Array<TankUsage>;
    muesliLogs: Array<DateIngredients>;
    batchCode: string;
}
export interface IngredientRow {
    qty: string;
    issueFromStores: string;
    lotNo: string;
    closingStock: string;
    ingredientName: string;
    openingStock: string;
}
export interface DateRange {
    toDate: DateText;
    fromDate: DateText;
}
export interface TankRoomLogEntry {
    id: bigint;
    remark: string;
    productRun: string;
    tankStatus: TankStatus;
    date: string;
    createdAt: bigint;
    createdBy: string;
    fillingTimeIn: string;
    fillingTimeOut: string;
    shift: string;
    updatedAt?: bigint;
    updatedBy?: string;
    cleaned: boolean;
    permanentTankNumber: string;
    reasonForHold: string;
    foodTankNo: string;
    correctiveAction: string;
    batchCode: string;
}
export type DateText = string;
export interface PackingLogEntry {
    id: bigint;
    mrp: string;
    bulkBagLotNo: string;
    bestBefore: string;
    caseCode: string;
    crew: string;
    date: string;
    netWeight: string;
    createdAt: bigint;
    createdBy: string;
    productName: string;
    updatedAt?: bigint;
    updatedBy?: string;
    tankBatchCodes: Array<string>;
    casePartitionSupplier: string;
    variety: string;
    machineNo: string;
    casePartitionLotNo: string;
    batchCode: string;
    bulkBagSupplier: string;
    mfgDate: string;
}
export interface PackingReference {
    date: string;
    productName: string;
    foodTankNos: Array<string>;
    batchCode: string;
}
export interface MuesliProcessLogEntry {
    id: bigint;
    run: string;
    date: string;
    createdAt: bigint;
    createdBy: string;
    shift: string;
    updatedAt?: bigint;
    updatedBy?: string;
    ingredients: Array<IngredientRow>;
    product: string;
}
export interface DateIngredients {
    run: string;
    date: string;
    shift: string;
    ingredients: Array<IngredientRow>;
    product: string;
}
export enum TankStatus {
    Feed = "Feed",
    Food = "Food",
    Hold = "Hold"
}
export interface backendInterface {
    addMuesliProcessLog(input: MuesliProcessLogInput): Promise<{
        __kind__: "ok";
        ok: MuesliProcessLogEntry;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addPackingLog(input: PackingLogInput): Promise<{
        __kind__: "ok";
        ok: PackingLogEntry;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addTankRoomLog(input: TankRoomLogInput): Promise<{
        __kind__: "ok";
        ok: TankRoomLogEntry;
    } | {
        __kind__: "err";
        err: string;
    }>;
    backwardTraceability(batchCode: string): Promise<BackwardTraceResult>;
    checkDuplicateBatchCode(batchCode: string): Promise<boolean>;
    checkDuplicateLotNumber(lotNumber: string, logBook: string): Promise<boolean>;
    deleteMuesliProcessLog(id: bigint): Promise<boolean>;
    deletePackingLog(id: bigint): Promise<boolean>;
    deleteTankRoomLog(id: bigint): Promise<boolean>;
    forwardTraceability(lotNo: string): Promise<ForwardTraceResult>;
    getDashboardStats(): Promise<DashboardStats>;
    getFlaggedRecords(): Promise<Array<FlaggedRecord>>;
    getMuesliProcessLogs(dateRange: DateRange | null): Promise<Array<MuesliProcessLogEntry>>;
    getPackingLogs(dateRange: DateRange | null): Promise<Array<PackingLogEntry>>;
    getShiftReport(date: string, shift: string): Promise<ShiftReport>;
    getTankRoomLogs(dateRange: DateRange | null): Promise<Array<TankRoomLogEntry>>;
    updateMuesliProcessLog(entry: MuesliProcessLogEntry): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updatePackingLog(entry: PackingLogEntry): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateTankRoomLog(entry: TankRoomLogEntry): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { DateRange as _DateRange, FlaggedRecord as _FlaggedRecord, IngredientRow as _IngredientRow, MuesliProcessLogEntry as _MuesliProcessLogEntry, PackingLogEntry as _PackingLogEntry, ShiftReport as _ShiftReport, TankRoomLogEntry as _TankRoomLogEntry, TankRoomLogInput as _TankRoomLogInput, TankStatus as _TankStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMuesliProcessLog(arg0: MuesliProcessLogInput): Promise<{
        __kind__: "ok";
        ok: MuesliProcessLogEntry;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addMuesliProcessLog(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMuesliProcessLog(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPackingLog(arg0: PackingLogInput): Promise<{
        __kind__: "ok";
        ok: PackingLogEntry;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addPackingLog(arg0);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPackingLog(arg0);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTankRoomLog(arg0: TankRoomLogInput): Promise<{
        __kind__: "ok";
        ok: TankRoomLogEntry;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addTankRoomLog(to_candid_TankRoomLogInput_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTankRoomLog(to_candid_TankRoomLogInput_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async backwardTraceability(arg0: string): Promise<BackwardTraceResult> {
        if (this.processError) {
            try {
                const result = await this.actor.backwardTraceability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.backwardTraceability(arg0);
            return result;
        }
    }
    async checkDuplicateBatchCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkDuplicateBatchCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkDuplicateBatchCode(arg0);
            return result;
        }
    }
    async checkDuplicateLotNumber(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkDuplicateLotNumber(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkDuplicateLotNumber(arg0, arg1);
            return result;
        }
    }
    async deleteMuesliProcessLog(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMuesliProcessLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMuesliProcessLog(arg0);
            return result;
        }
    }
    async deletePackingLog(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePackingLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePackingLog(arg0);
            return result;
        }
    }
    async deleteTankRoomLog(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTankRoomLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTankRoomLog(arg0);
            return result;
        }
    }
    async forwardTraceability(arg0: string): Promise<ForwardTraceResult> {
        if (this.processError) {
            try {
                const result = await this.actor.forwardTraceability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forwardTraceability(arg0);
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getFlaggedRecords(): Promise<Array<FlaggedRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlaggedRecords();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlaggedRecords();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMuesliProcessLogs(arg0: DateRange | null): Promise<Array<MuesliProcessLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMuesliProcessLogs(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMuesliProcessLogs(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPackingLogs(arg0: DateRange | null): Promise<Array<PackingLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackingLogs(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackingLogs(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShiftReport(arg0: string, arg1: string): Promise<ShiftReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getShiftReport(arg0, arg1);
                return from_candid_ShiftReport_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShiftReport(arg0, arg1);
            return from_candid_ShiftReport_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTankRoomLogs(arg0: DateRange | null): Promise<Array<TankRoomLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTankRoomLogs(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTankRoomLogs(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMuesliProcessLog(arg0: MuesliProcessLogEntry): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMuesliProcessLog(to_candid_MuesliProcessLogEntry_n27(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMuesliProcessLog(to_candid_MuesliProcessLogEntry_n27(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePackingLog(arg0: PackingLogEntry): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePackingLog(to_candid_PackingLogEntry_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePackingLog(to_candid_PackingLogEntry_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTankRoomLog(arg0: TankRoomLogEntry): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTankRoomLog(to_candid_TankRoomLogEntry_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTankRoomLog(to_candid_TankRoomLogEntry_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_FlaggedRecord_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlaggedRecord): FlaggedRecord {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_MuesliProcessLogEntry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MuesliProcessLogEntry): MuesliProcessLogEntry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_PackingLogEntry_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PackingLogEntry): PackingLogEntry {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ShiftReport_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShiftReport): ShiftReport {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_TankRoomLogEntry_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TankRoomLogEntry): TankRoomLogEntry {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TankStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TankStatus): TankStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    remark: string;
    productRun: string;
    tankStatus: _TankStatus;
    date: string;
    createdAt: bigint;
    createdBy: string;
    fillingTimeIn: string;
    fillingTimeOut: string;
    shift: string;
    updatedAt: [] | [bigint];
    updatedBy: [] | [string];
    cleaned: boolean;
    permanentTankNumber: string;
    reasonForHold: string;
    foodTankNo: string;
    correctiveAction: string;
    batchCode: string;
}): {
    id: bigint;
    remark: string;
    productRun: string;
    tankStatus: TankStatus;
    date: string;
    createdAt: bigint;
    createdBy: string;
    fillingTimeIn: string;
    fillingTimeOut: string;
    shift: string;
    updatedAt?: bigint;
    updatedBy?: string;
    cleaned: boolean;
    permanentTankNumber: string;
    reasonForHold: string;
    foodTankNo: string;
    correctiveAction: string;
    batchCode: string;
} {
    return {
        id: value.id,
        remark: value.remark,
        productRun: value.productRun,
        tankStatus: from_candid_TankStatus_n16(_uploadFile, _downloadFile, value.tankStatus),
        date: value.date,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        fillingTimeIn: value.fillingTimeIn,
        fillingTimeOut: value.fillingTimeOut,
        shift: value.shift,
        updatedAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.updatedAt)),
        updatedBy: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.updatedBy)),
        cleaned: value.cleaned,
        permanentTankNumber: value.permanentTankNumber,
        reasonForHold: value.reasonForHold,
        foodTankNo: value.foodTankNo,
        correctiveAction: value.correctiveAction,
        batchCode: value.batchCode
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedLotNumbers: Array<string>;
    linkedBatchCodes: Array<string>;
    tankEntry: _TankRoomLogEntry;
}): {
    linkedLotNumbers: Array<string>;
    linkedBatchCodes: Array<string>;
    tankEntry: TankRoomLogEntry;
} {
    return {
        linkedLotNumbers: value.linkedLotNumbers,
        linkedBatchCodes: value.linkedBatchCodes,
        tankEntry: from_candid_TankRoomLogEntry_n14(_uploadFile, _downloadFile, value.tankEntry)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tankEntries: Array<_TankRoomLogEntry>;
    rawMaterialEntries: Array<_MuesliProcessLogEntry>;
    date: string;
    shift: string;
    packingEntries: Array<_PackingLogEntry>;
}): {
    tankEntries: Array<TankRoomLogEntry>;
    rawMaterialEntries: Array<MuesliProcessLogEntry>;
    date: string;
    shift: string;
    packingEntries: Array<PackingLogEntry>;
} {
    return {
        tankEntries: from_candid_vec_n26(_uploadFile, _downloadFile, value.tankEntries),
        rawMaterialEntries: from_candid_vec_n22(_uploadFile, _downloadFile, value.rawMaterialEntries),
        date: value.date,
        shift: value.shift,
        packingEntries: from_candid_vec_n23(_uploadFile, _downloadFile, value.packingEntries)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    run: string;
    date: string;
    createdAt: bigint;
    createdBy: string;
    shift: string;
    updatedAt: [] | [bigint];
    updatedBy: [] | [string];
    ingredients: Array<_IngredientRow>;
    product: string;
}): {
    id: bigint;
    run: string;
    date: string;
    createdAt: bigint;
    createdBy: string;
    shift: string;
    updatedAt?: bigint;
    updatedBy?: string;
    ingredients: Array<IngredientRow>;
    product: string;
} {
    return {
        id: value.id,
        run: value.run,
        date: value.date,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        shift: value.shift,
        updatedAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.updatedAt)),
        updatedBy: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.updatedBy)),
        ingredients: value.ingredients,
        product: value.product
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    mrp: string;
    bulkBagLotNo: string;
    bestBefore: string;
    caseCode: string;
    crew: string;
    date: string;
    netWeight: string;
    createdAt: bigint;
    createdBy: string;
    productName: string;
    updatedAt: [] | [bigint];
    updatedBy: [] | [string];
    tankBatchCodes: Array<string>;
    casePartitionSupplier: string;
    variety: string;
    machineNo: string;
    casePartitionLotNo: string;
    batchCode: string;
    bulkBagSupplier: string;
    mfgDate: string;
}): {
    id: bigint;
    mrp: string;
    bulkBagLotNo: string;
    bestBefore: string;
    caseCode: string;
    crew: string;
    date: string;
    netWeight: string;
    createdAt: bigint;
    createdBy: string;
    productName: string;
    updatedAt?: bigint;
    updatedBy?: string;
    tankBatchCodes: Array<string>;
    casePartitionSupplier: string;
    variety: string;
    machineNo: string;
    casePartitionLotNo: string;
    batchCode: string;
    bulkBagSupplier: string;
    mfgDate: string;
} {
    return {
        id: value.id,
        mrp: value.mrp,
        bulkBagLotNo: value.bulkBagLotNo,
        bestBefore: value.bestBefore,
        caseCode: value.caseCode,
        crew: value.crew,
        date: value.date,
        netWeight: value.netWeight,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        productName: value.productName,
        updatedAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.updatedAt)),
        updatedBy: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.updatedBy)),
        tankBatchCodes: value.tankBatchCodes,
        casePartitionSupplier: value.casePartitionSupplier,
        variety: value.variety,
        machineNo: value.machineNo,
        casePartitionLotNo: value.casePartitionLotNo,
        batchCode: value.batchCode,
        bulkBagSupplier: value.bulkBagSupplier,
        mfgDate: value.mfgDate
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _MuesliProcessLogEntry;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: MuesliProcessLogEntry;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_MuesliProcessLogEntry_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TankRoomLogEntry;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TankRoomLogEntry;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_TankRoomLogEntry_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Feed: null;
} | {
    Food: null;
} | {
    Hold: null;
}): TankStatus {
    return "Feed" in value ? TankStatus.Feed : "Food" in value ? TankStatus.Food : "Hold" in value ? TankStatus.Hold : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PackingLogEntry;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PackingLogEntry;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PackingLogEntry_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FlaggedRecord>): Array<FlaggedRecord> {
    return value.map((x)=>from_candid_FlaggedRecord_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MuesliProcessLogEntry>): Array<MuesliProcessLogEntry> {
    return value.map((x)=>from_candid_MuesliProcessLogEntry_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PackingLogEntry>): Array<PackingLogEntry> {
    return value.map((x)=>from_candid_PackingLogEntry_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TankRoomLogEntry>): Array<TankRoomLogEntry> {
    return value.map((x)=>from_candid_TankRoomLogEntry_n14(_uploadFile, _downloadFile, x));
}
function to_candid_MuesliProcessLogEntry_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MuesliProcessLogEntry): _MuesliProcessLogEntry {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_PackingLogEntry_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PackingLogEntry): _PackingLogEntry {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_TankRoomLogEntry_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TankRoomLogEntry): _TankRoomLogEntry {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_TankRoomLogInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TankRoomLogInput): _TankRoomLogInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_TankStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TankStatus): _TankStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DateRange | null): [] | [_DateRange] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    remark: string;
    productRun: string;
    tankStatus: TankStatus;
    date: string;
    fillingTimeIn: string;
    fillingTimeOut: string;
    shift: string;
    cleaned: boolean;
    permanentTankNumber: string;
    reasonForHold: string;
    foodTankNo: string;
    correctiveAction: string;
    batchCode: string;
}): {
    remark: string;
    productRun: string;
    tankStatus: _TankStatus;
    date: string;
    fillingTimeIn: string;
    fillingTimeOut: string;
    shift: string;
    cleaned: boolean;
    permanentTankNumber: string;
    reasonForHold: string;
    foodTankNo: string;
    correctiveAction: string;
    batchCode: string;
} {
    return {
        remark: value.remark,
        productRun: value.productRun,
        tankStatus: to_candid_TankStatus_n11(_uploadFile, _downloadFile, value.tankStatus),
        date: value.date,
        fillingTimeIn: value.fillingTimeIn,
        fillingTimeOut: value.fillingTimeOut,
        shift: value.shift,
        cleaned: value.cleaned,
        permanentTankNumber: value.permanentTankNumber,
        reasonForHold: value.reasonForHold,
        foodTankNo: value.foodTankNo,
        correctiveAction: value.correctiveAction,
        batchCode: value.batchCode
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    run: string;
    date: string;
    createdAt: bigint;
    createdBy: string;
    shift: string;
    updatedAt?: bigint;
    updatedBy?: string;
    ingredients: Array<IngredientRow>;
    product: string;
}): {
    id: bigint;
    run: string;
    date: string;
    createdAt: bigint;
    createdBy: string;
    shift: string;
    updatedAt: [] | [bigint];
    updatedBy: [] | [string];
    ingredients: Array<_IngredientRow>;
    product: string;
} {
    return {
        id: value.id,
        run: value.run,
        date: value.date,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        shift: value.shift,
        updatedAt: value.updatedAt ? candid_some(value.updatedAt) : candid_none(),
        updatedBy: value.updatedBy ? candid_some(value.updatedBy) : candid_none(),
        ingredients: value.ingredients,
        product: value.product
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    mrp: string;
    bulkBagLotNo: string;
    bestBefore: string;
    caseCode: string;
    crew: string;
    date: string;
    netWeight: string;
    createdAt: bigint;
    createdBy: string;
    productName: string;
    updatedAt?: bigint;
    updatedBy?: string;
    tankBatchCodes: Array<string>;
    casePartitionSupplier: string;
    variety: string;
    machineNo: string;
    casePartitionLotNo: string;
    batchCode: string;
    bulkBagSupplier: string;
    mfgDate: string;
}): {
    id: bigint;
    mrp: string;
    bulkBagLotNo: string;
    bestBefore: string;
    caseCode: string;
    crew: string;
    date: string;
    netWeight: string;
    createdAt: bigint;
    createdBy: string;
    productName: string;
    updatedAt: [] | [bigint];
    updatedBy: [] | [string];
    tankBatchCodes: Array<string>;
    casePartitionSupplier: string;
    variety: string;
    machineNo: string;
    casePartitionLotNo: string;
    batchCode: string;
    bulkBagSupplier: string;
    mfgDate: string;
} {
    return {
        id: value.id,
        mrp: value.mrp,
        bulkBagLotNo: value.bulkBagLotNo,
        bestBefore: value.bestBefore,
        caseCode: value.caseCode,
        crew: value.crew,
        date: value.date,
        netWeight: value.netWeight,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        productName: value.productName,
        updatedAt: value.updatedAt ? candid_some(value.updatedAt) : candid_none(),
        updatedBy: value.updatedBy ? candid_some(value.updatedBy) : candid_none(),
        tankBatchCodes: value.tankBatchCodes,
        casePartitionSupplier: value.casePartitionSupplier,
        variety: value.variety,
        machineNo: value.machineNo,
        casePartitionLotNo: value.casePartitionLotNo,
        batchCode: value.batchCode,
        bulkBagSupplier: value.bulkBagSupplier,
        mfgDate: value.mfgDate
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    remark: string;
    productRun: string;
    tankStatus: TankStatus;
    date: string;
    createdAt: bigint;
    createdBy: string;
    fillingTimeIn: string;
    fillingTimeOut: string;
    shift: string;
    updatedAt?: bigint;
    updatedBy?: string;
    cleaned: boolean;
    permanentTankNumber: string;
    reasonForHold: string;
    foodTankNo: string;
    correctiveAction: string;
    batchCode: string;
}): {
    id: bigint;
    remark: string;
    productRun: string;
    tankStatus: _TankStatus;
    date: string;
    createdAt: bigint;
    createdBy: string;
    fillingTimeIn: string;
    fillingTimeOut: string;
    shift: string;
    updatedAt: [] | [bigint];
    updatedBy: [] | [string];
    cleaned: boolean;
    permanentTankNumber: string;
    reasonForHold: string;
    foodTankNo: string;
    correctiveAction: string;
    batchCode: string;
} {
    return {
        id: value.id,
        remark: value.remark,
        productRun: value.productRun,
        tankStatus: to_candid_TankStatus_n11(_uploadFile, _downloadFile, value.tankStatus),
        date: value.date,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        fillingTimeIn: value.fillingTimeIn,
        fillingTimeOut: value.fillingTimeOut,
        shift: value.shift,
        updatedAt: value.updatedAt ? candid_some(value.updatedAt) : candid_none(),
        updatedBy: value.updatedBy ? candid_some(value.updatedBy) : candid_none(),
        cleaned: value.cleaned,
        permanentTankNumber: value.permanentTankNumber,
        reasonForHold: value.reasonForHold,
        foodTankNo: value.foodTankNo,
        correctiveAction: value.correctiveAction,
        batchCode: value.batchCode
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TankStatus): {
    Feed: null;
} | {
    Food: null;
} | {
    Hold: null;
} {
    return value == TankStatus.Feed ? {
        Feed: null
    } : value == TankStatus.Food ? {
        Food: null
    } : value == TankStatus.Hold ? {
        Hold: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
